/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __LINE_DETECTION_ALL_TYPES_H__
#define __LINE_DETECTION_ALL_TYPES_H__

#include <line_detection/types/type_definitions.h>


#endif /* __LINE_DETECTION_ALL_TYPES_H__ */
