/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __LINE_DETECTION_TYPE_DEFINITIONS_H__
#define __LINE_DETECTION_TYPE_DEFINITIONS_H__


#endif /* __LINE_DETECTION_TYPE_DEFINITIONS_H__ */
